### ISSUE TITLE
Windows: tests fail due to sending logs to /dev/null

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/chef-core#17]
# Describe the problem

All tests currently fail on windows because during setup, the logger is configured to send logging to `/dev/null`, which does not exist.

```
47) ChefCore::Actions::InstallChef#perform_local_install performs the steps necessary to perform an installation
--
  | Failure/Error: location = File.open(location, "w+")
  |  
  | Errno::ENOENT:
  | No such file or directory @ rb_sysopen - /dev/null
  | # ./lib/chef_core/log.rb:29:in `initialize'
  | # ./lib/chef_core/log.rb:29:in `open'
  | # ./lib/chef_core/log.rb:29:in `setup'
  | # ./spec/spec_helper.rb:90:in `block (2 levels) in <top (required)>'

```

## Stacktrace

<details><summary>  </summary>
```
```
https://github.com/chef/chef-core/blob/e1c1783c44bb833fd34d9293621949c37b9498d1/spec/spec_helper.rb#L90

</details>

**Comment by nandanhegde73** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
